
[font]
size = 12.0
builtin_box_drawing = false

[font.normal]
# family = "Mononoki Nerd Font"
family = "FiraCode Nerd Font"
# family = "Hack Nerd Font"
# family = "Source Code Pro Nerd Font"  
# family = "Cascadia Code Nerd Font"
# family = "Victor Mono Nerd Font"
# family = "Iosevka Nerd Font"
# family = "SF Mono Nerd Font"
# family = "Inconsolata Nerd Font"
# family = "Ubuntu Mono Nerd Font"
# family = "Anonymous Pro Nerd Font"
# family = "Cousine Nerd Font"
# family = "IBM Plex Mono Nerd Font"
# family = "SpaceMono Nerd Font"
# family = "Roboto Mono Nerd Font"
# family = "DejaVu Sans Mono Nerd Font"
# family = "Liberation Mono Nerd Font"

# Personal favs for crispness:
# - Hack - very clean
# - Iosevka - super crisp, narrow
# - Victor Mono - has cursive italics
# - Cascadia Code - Microsoft's new hotness

# [[keyboard.bindings]]
# chars = "\u001B[27;5;9~"
# key = "Tab"
# mods = "Control"

# [[keyboard.bindings]]
# chars = "\u001B[27;6;9~"
# key = "Tab"
# mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
save_to_clipboard = true

[window]
#decorations = "none"
opacity = 0.91

[window.padding]
x = 10
y = 5

[general]
live_config_reload = true

import = [

# "~/.config/alacritty/themes/themes/afterglow.toml"
# "~/.config/alacritty/themes/themes/alabaster_dark.toml"
# "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
# "~/.config/alacritty/themes/themes/argonaut.toml"
# "~/.config/alacritty/themes/themes/ashes_dark.toml"
# "~/.config/alacritty/themes/themes/aura.toml"
# "~/.config/alacritty/themes/themes/ayu_dark.toml"
# "~/.config/alacritty/themes/themes/baitong.toml"
# "~/.config/alacritty/themes/themes/base16_default_dark.toml"
# "~/.config/alacritty/themes/themes/blood_moon.toml"
# "~/.config/alacritty/themes/themes/bluish.toml"
# "~/.config/alacritty/themes/themes/breeze.toml"
# "~/.config/alacritty/themes/themes/campbell.toml"
# "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
# "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
# "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
# "~/.config/alacritty/themes/themes/catppuccin.toml"
# "~/.config/alacritty/themes/themes/challenger_deep.toml"
# "~/.config/alacritty/themes/themes/Cobalt2.toml"
# "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
# "~/.config/alacritty/themes/themes/darcula.toml"
# "~/.config/alacritty/themes/themes/dark_pastels.toml"
# "~/.config/alacritty/themes/themes/deep_space.toml"
# "~/.config/alacritty/themes/themes/doom_one.toml"
# "~/.config/alacritty/themes/themes/dracula.toml"
# "~/.config/alacritty/themes/themes/everforest_dark.toml"
# "~/.config/alacritty/themes/themes/falcon.toml"
# "~/.config/alacritty/themes/themes/flat_remix.toml"
# "~/.config/alacritty/themes/themes/flexoki.toml"
# "~/.config/alacritty/themes/themes/github_dark_colorblind.toml"
# "~/.config/alacritty/themes/themes/github_dark_default.toml"
# "~/.config/alacritty/themes/themes/github_dark_dimmed.toml"
# "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
# "~/.config/alacritty/themes/themes/github_dark.toml"
# "~/.config/alacritty/themes/themes/github_dark_tritanopia.toml"
# "~/.config/alacritty/themes/themes/github_light_default.toml"
# "~/.config/alacritty/themes/themes/github_light.toml"
# "~/.config/alacritty/themes/themes/gnome_terminal.toml"
# "~/.config/alacritty/themes/themes/google.toml"
# "~/.config/alacritty/themes/themes/gotham.toml"
# "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
# "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
# "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
# "~/.config/alacritty/themes/themes/gruvbox_material.toml"
# "~/.config/alacritty/themes/themes/hardhacker.toml"
# "~/.config/alacritty/themes/themes/high_contrast.toml"
# "~/.config/alacritty/themes/themes/horizon-dark.toml"
"~/.config/alacritty/themes/themes/hyper.toml"
# "~/.config/alacritty/themes/themes/inferno.toml"
# "~/.config/alacritty/themes/themes/iris.toml"
# "~/.config/alacritty/themes/themes/iterm.toml"
# "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
# "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
# "~/.config/alacritty/themes/themes/konsole_linux.toml"
# "~/.config/alacritty/themes/themes/low_contrast.toml"
# "~/.config/alacritty/themes/themes/Mariana.toml"
# "~/.config/alacritty/themes/themes/marine_dark.toml"
# "~/.config/alacritty/themes/themes/material_theme_mod.toml"
# "~/.config/alacritty/themes/themes/material_theme.toml"
# "~/.config/alacritty/themes/themes/meliora.toml"
# "~/.config/alacritty/themes/themes/midnight-haze.toml"
# "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
# "~/.config/alacritty/themes/themes/moonlight_ii_vscode.toml"
# "~/.config/alacritty/themes/themes/msx.toml"
# "~/.config/alacritty/themes/themes/nightfox.toml"
# "~/.config/alacritty/themes/themes/nordic.toml"
# "~/.config/alacritty/themes/themes/nord.toml"
# "~/.config/alacritty/themes/themes/oceanic_next.toml"
# "~/.config/alacritty/themes/themes/omni.toml"
# "~/.config/alacritty/themes/themes/one_dark.toml"
# "~/.config/alacritty/themes/themes/palenight.toml"
# "~/.config/alacritty/themes/themes/papercolor_dark.toml"
# "~/.config/alacritty/themes/themes/rainbow.toml"
# "~/.config/alacritty/themes/themes/remedy_dark.toml"
# "~/.config/alacritty/themes/themes/rose-pine-moon.toml"
# "~/.config/alacritty/themes/themes/rose-pine.toml"
# "~/.config/alacritty/themes/themes/seashells.toml"
# "~/.config/alacritty/themes/themes/smoooooth.toml"
# "~/.config/alacritty/themes/themes/snazzy.toml"
# "~/.config/alacritty/themes/themes/solarized_dark.toml"
# "~/.config/alacritty/themes/themes/solarized_osaka.toml"
# "~/.config/alacritty/themes/themes/taerminal.toml"
# "~/.config/alacritty/themes/themes/tango_dark.toml"
# "~/.config/alacritty/themes/themes/tender.toml"
# "~/.config/alacritty/themes/themes/thelovelace.toml"
# "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
# "~/.config/alacritty/themes/themes/tokyo-night.toml"
# "~/.config/alacritty/themes/themes/tomorrow_night.toml"
# "~/.config/alacritty/themes/themes/ubuntu.toml"
# "~/.config/alacritty/themes/themes/wombat.toml"
# "~/.config/alacritty/themes/themes/zenburn.toml"
  
# "~/.config/alacritty/themes/themes/pastel_dark.toml"
# "~/.config/alacritty/themes/themes/pencil_dark.toml" # MAIN THEME
# "~/.config/alacritty/themes/themes/carbonfox.toml"
# "~/.config/alacritty/themes/themes/terminal_app.toml"
# "~/.config/alacritty/themes/themes/citylights.toml"
# "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
# "~/.config/alacritty/themes/themes/xterm.toml"
# "~/.config/alacritty/themes/themes/monokai_pro.toml"

]
# !!!Eye Bleach Mode!!!
# "~/.config/alacritty/themes/themes/solarized_light.toml"
# "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
# "~/.config/alacritty/themes/themes/pencil_light.toml"
# "~/.config/alacritty/themes/themes/papertheme.toml"
# "~/.config/alacritty/themes/themes/papercolor_light.toml"
# "~/.config/alacritty/themes/themes/nord_light.toml"
# "~/.config/alacritty/themes/themes/noctis-lux.toml"
# "~/.config/alacritty/themes/themes/night_owlish_light.toml"
# "~/.config/alacritty/themes/themes/gruvbox_material_medium_light.toml"
# "~/.config/alacritty/themes/themes/gruvbox_material_hard_light.toml"
# "~/.config/alacritty/themes/themes/gruvbox_light.toml"
# "~/.config/alacritty/themes/themes/github_light_tritanopia.toml"
# "~/.config/alacritty/themes/themes/github_light_high_contrast.toml"
# "~/.config/alacritty/themes/themes/github_light_colorblind.toml"
# "~/.config/alacritty/themes/themes/everforest_light.toml"
# "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
# "~/.config/alacritty/themes/themes/ayu_light.toml"
# "~/.config/alacritty/themes/themes/atom_one_light.toml"
# "~/.config/alacritty/themes/themes/ashes_light.toml"
# "~/.config/alacritty/themes/themes/alabaster.toml"
