[username]
show_always = true 
style_user  = "#b16286 bold"
style_root  = "#cc241d bold"
format      = "[$user]($style)"
disabled    = false

[hostname]
ssh_only   = false
format     = "@[$hostname](bold #f65d0e) "
ssh_symbol = 'ğŸŒ '
disabled   = false

[directory]
truncate_to_repo          = false
truncation_length         = 3
fish_style_pwd_dir_length = 1
truncation_symbol         = "â€¦/"
style                     = "#8ec07c bold"

[git_branch]
style = "#458588 bold"

[git_status]
style      = "bold white"
format     = '([\($all_status$ahead_behind\)]($style) )'
conflicted = "[=](#cc241d bold)"
ahead      = "[â‡¡](#98971a bold)"
behind     = "[â‡£](#cc241d bold)"
diverged   = "[â‡•](#cc241d bold)"
up_to_date = ""
untracked  = "[?](#cc241d bold)"
stashed    = "[$](#f65d0e bold)"
modified   = "[!](#cc241d bold)"
renamed    = "[Â»](#cc241d bold)"
deleted    = "[âœ˜](#cc241d bold)"
staged     = "[+](#98971a bold)"
disabled   = false

[character]
vicmd_symbol = '[â®](bold #f65d0e) '
