[metadata]
name = "env"
description = "A channel to select from environment variables"

[source]
command = "$HOME/.config/television/cable/env.sh source"

[preview]
command = "echo '{}' | $HOME/.config/television/cable/env.sh preview"

[ui]
layout = "portrait"

[keybindings]
shortcut = "f3"

[ui.preview_panel]
size = 20
header = "{split:=:0}"

[actions.name]
description = "Output the variable name instead of the value"
command = "echo '{split:=:0}'"
mode = "execute"
